#!/bin/bash

# Make dbus happy! Yay!
systemd-machine-id-setup
clear

# Launch the wizard.
/usr/libexec/aosc-os-oobe/aosc-os-oobe-cli

source /etc/locale.conf
export LANG

export TEXTDOMAIN=aosc-os-oobe-launcher

PROMPT=$"Please wait while the setup program performs one last cleanup operation.
Your device will reboot automatically once it is finished."
# Clean up
echo -e "$PROMPT"
oma --no-progress --no-bell purge --yes aosc-os-oobe-cli
oma --no-progress --no-bell autoremove --yes

# Apply the static hostname to the transient hostname.
HOSTNAME="$(hostnamectl hostname --static)"
export HOSTNAME
hostnamectl hostname --transient "$HOSTNAME"

sync
reboot -f
