on:
  push:
    tags:
    - '*'


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22
      - name: Install dependencies
        run: cd oobe-gui && yarn
      - name: Build
        run: cd oobe-gui && yarn vite build && tar -cvf dist.tar ./dist && xz -T0 dist.tar
      - name: Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: oobe-gui/dist.tar.xz
          file_glob: true
          tag: ${{ github.ref }}
          overwrite: true
